#
#   /$$$$$$
#  /$$__  $$
# | $$  \__/  /$$$$$$  /$$$$$$$   /$$$$$$   /$$$$$$
# |  $$$$$$  /$$__  $$| $$__  $$ |____  $$ /$$__  $$
#  \____  $$| $$  \ $$| $$  \ $$  /$$$$$$$| $$  \__/
#  /$$  \ $$| $$  | $$| $$  | $$ /$$__  $$| $$
# |  $$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$| $$
#  \______/  \______/ |__/  |__/ \_______/|__/
#
# Brauchst du Hilfe? https://jonesdev.xyz/discord
# Source code: https://github.com/jonesdevelopment/sonar
# Dokumentation: https://docs.jonesdev.xyz/administration/configuring-sonar
# Copyright Jones Development and Sonar Contributors, lizenziert unter GPL-3.0
#

# Generelle Einstellungen für Sonar
general:
  # Should Sonar automatically check for new updates?
  # Sonar uses the GitHub API to check if the current version is outdated
  check-for-updates: true
  # Soll Sonar die IP Adressen von Spielern in der Konsole anzeigen?
  log-player-addresses: true
  # Maximale Anzahl an Spielern mit derselben IP Adresse
  max-online-per-ip: 3

# Sensitivitätseinstellungen für Angriffstracker
# Bearbeite diese Einstellungen, nur wenn du weißt, was du tust!
attack-tracker:
  # Minimale Anzahl an neuen Spielern damit ein Angriff als solcher erkannt wird
  min-players-for-attack: 8
  # Anzahl an Millisekunden bis ein Angriff vorbei ist
  min-attack-duration: 30000
  # Anzahl an gemeldenten Vorfällen damit ein Angriff als solcher erkannt wird
  # Diese Zahl repräsentiert einen Puffer, um falsche Angriffsbenachrichtigungen zu filtern
  min-attack-threshold: 2
  # Anzahl an Millisekunden die vergehen muss damit eine neue Attacke erkannt wird
  attack-cooldown-delay: 3000

# Du kannst Sonar mit einer Datenbank verbinden, um verifizierte Spieler zu speichern
# Beachte: IP adressen werden im Klartext gespeichert. Du bist für die Sicherheit der Datenbank verantwortlich
database:
  # Typ von Datenbank die Sonar verwenden soll, um verifizierte Spielerdaten zu speichern
  # Mögliche Typen: NONE, MYSQL, MARIADB, H2
  type: NONE
  # Datei im Plugin-Verzeichnis von Sonar, die für die H2-Datenbank verwendet wird
  filename: verified_players
  # HOST für die Authentifizierung mit der SQL Datenbank
  host: localhost
  # Port für die Authentifizierung mit der SQL Datenbank
  port: 3306
  # Name der SQL Datenbank
  name: sonar
  # Username für die Authentifizierung mit der SQL Datenbank
  username: ''
  # Password für die Authentifizierung mit der SQL Datenbank
  password: ''
  # Wie viele Tage soll Sonar verifizierte Spielerdaten in der Datenbank behalten?
  maximum-age: 5

# Jede neue Login-Anfrage wird in eine Warteschlange eingereiht, um Spam-Beitrittsangriffe zu vermeiden
# Die Warteschlange wird alle 1 Sekunde (20 Ticks) aktualisiert
queue:
  # Maximale Anzahl an gleichzeitigen Abfragen der Warteschlange pro 1 Sekunde
  max-polls: 30

# Jeder neue Spieler, der das erste Mal beitritt, wird zu
# einem leichtgewichtigen Limbo-Server gesendet, wo fortgeschrittene Bot-Überprüfungen durchgeführt werden
verification:
  # Wann sollte Sonar neue Spieler überprüfen?
  # Mögliche Typen: ALWAYS, DURING_ATTACK
  # - ALWAYS: Neue Spieler werden immer überprüft (Empfohlen)
  # - DURING_ATTACK: Neue Spieler werden nur während eines Angriffs überprüft
  timing: ALWAYS
  checks:
    # Überprüft, ob die Fallbewegung der Spieler der Gravitationsformel von Minecraft folgt
    # Alle vorhergesagten Bewegungen werden vorausberechnet, um die Leistung zu sparen
    gravity:
      # Soll Sonar auf gültige Client-Gravitation prüfen? (Empfohlen)
      enabled: true
      # Soll Sonar den Spieler dazu bringen, ein CAPTCHA zu lösen, wenn er die Schwerkraftprüfung nicht besteht?
      captcha-on-fail: false
      # Maximale Anzahl an Ticks, die der Spieler fallen muss, um die Plattform erreichen zu dürfen
      max-movement-ticks: 8

    # Prüft, ob der Spieler mit Blöcken kollidiert, die unter ihm gespawnt sind
    collision:
      # Soll Sonar prüfen, ob der Spieler mit Blöcken kollidiert? (Empfohlen)
      enabled: true

    # Überprüft, ob der Spieler beim Einsteigen in ein Boot die richtigen Pakete sendet
    vehicle:
      # Sollte Sonar prüfen, ob der Spieler richtig in ein Fahrzeug einsteigt?
      enabled: true
      # Mindestanzahl der vom Client gesendeten Pakete
      minimum-packets: 2

    # Lässt den Spieler einen Code von einer virtuellen Karte im Chat eingeben
    map-captcha:
      # Wann sollte Sonar den Spieler ein CAPTCHA lösen lassen?
      # Mögliche Typen: ALWAYS, DURING_ATTACK, NEVER
      # - ALWAYS: Neue Spieler erhalten immer ein CAPTCHA
      # - DURING_ATTACK: Neue Spieler erhalten nur während eines Angriffs ein CAPTCHA
      # - NEVER: Neue Spieler erhalten nie ein CAPTCHA (Empfohlen)
      timing: NEVER
      # Pfad zum Hintergrundbild, das Sonar für das CAPTCHA verwendet
      # Wenn das Bild nicht gefunden wird, wird ein Rauschen als Standardhintergrund verwendet
      # Sie können hier einfach den Namen der Datei eingeben, wenn sich die Datei im Plugin-Verzeichnis befindet
      background: ''
      # Stil der Karte CAPTCHA (Standard: 'modern').
      # Um das alte Design zu verwenden, setzen Sie dies auf 'legacy'.
      style: 'modern'
      # Wie viele Antworten soll Sonar vorbereiten?
      # Dieser Vorgang erfolgt asynchron im Hintergrund
      precompute: 500
      # Wie lange soll Sonar warten, bis der Spieler das CAPTCHA nicht besteht?
      # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
      max-duration: 30000
      # Wie oft muss ein Spieler das CAPTCHA nicht bestehen, bevor er die Überprüfung nicht besteht?
      max-tries: 3
      # Zeichen (Buchstaben und Zahlen), die im Antwort-CAPTCHA erscheinen dürfen
      # Es wird nicht empfohlen, Zahlen oder Buchstaben hinzuzufügen, die einander ähneln könnten
      alphabet: 'abcdefhjkmnoprstuxyz'

    # Überprüft, ob die Spieler eine gültige Client-Marke an den Server senden
    client-brand:
      # Soll Sonar auf gültige Client-Marken prüfen? (Empfohlen)
      enabled: true
      # Regex zur Validierung von Client-Marken während der Überprüfung
      valid-regex: ^[!-~ ]+$
      # Maximale Länge der Client-Marke während der Überprüfung
      max-length: 64

    # Regex zur Validierung von Benutzernamen während der Überprüfung
    valid-name-regex: ^[a-zA-Z0-9_]+$
    # Regex zur Validierung der Client-Spracheinstellung während der Überprüfung
    valid-locale-regex: ^[a-zA-Z_]+$

  # Wenn aktiviert, wird der Player zurück zum Ursprungsserver gesendet,
  # falls dieser die der Bot-Verifizierung erfolgreich besteht.
  # Diese Funktion wurde von Mojang in Minecraft Version 1.20.5 eingeführt
  # https://docs.jonesdev.xyz/administration/configuring-sonar/configuring-the-verification/using-1.20.5+-transfers
  transfer:
    # Sollte Sonar den Spieler auf den Ursprungsserver senden (anstatt ihn zu kicken)?
    # Damit dies funktioniert, müssen Sie die Funktion in der Konfiguration Ihres Servers aktivieren.
    # Darüber hinaus möchten Sie möglicherweise die Begrenzung der Anmelderate reduzieren
    # wird von Velocity oder anderen Proxys/Plugins durchgeführt, da dies das verhindern könnte
    # Spieler konnte nicht korrekt übertragen werden.
    # Wenn Ihr Server es erlaubt, dass Bedrock-Spieler über Geyser beitreten können, stellen Sie sicher, dass Sie das
    # TransferTool für Geyser einrichten, damit Bedrock-Spieler auf den richtigen Server umgeleitet werden.
    # https://github.com/onebeastchris/TransferTool
    enabled: false
    # Auf welchen Server soll Sonar den Spieler übertragen, wenn die Verifizierung bestanden wurde?
    # Bitte geben Sie die Server-IP ein, die von Spielern verwendet wird, um sich zu verbinden.
    # Sie können beispielsweise "mc.hypixel.net" oder eine direkte IP wie "1.1.1.1" verwenden.
    destination-host: "play.my-server.com"
    # Welchen Port sollte Sonar verwenden, wenn der Spieler auf den Ursprungsserver gesendet wird?
    # Wenn Ihr Server keinen Port zum Herstellen einer Verbindung benötigt, können Sie diesen auf 25565 belassen.
    destination-port: 25565

  # Der Spielmodus des Spielers während der Überprüfung
  # Mögliche Typen: SURVIVAL, CREATIVE, ADVENTURE
  # - SURVIVAL: alle UI-Komponenten sind sichtbar
  # - CREATIVE: Gesundheit und Hunger sind versteckt
  # - ADVENTURE: alle UI-Komponenten sind sichtbar
  gamemode: ADVENTURE
  # Tageszeit in der Verifizierungswelt
  # Alle Tageszeiten finden Sie hier:
  # https://minecraft.wiki/w/Daylight_cycle
  # Dies ist nur eine visuelle Einstellung und ändert nichts am Verifizierungsprozess!
  # Wenn dieser Wert auf 1000 gesetzt ist, wird das Paket nicht gesendet.
  time-of-day: 1000
  # Sonar speichert die meisten Pakete, die es an den Client sendet, einschließlich des LoginSuccess-Pakets.
  # Welchen Benutzernamen soll Sonar für das LoginSuccess-Paket verwenden?
  # Der Benutzername ist für den Spieler ohne Änderungen am Client nicht sichtbar
  cached-username: "Sonar"
  # Soll Sonar neue Überprüfungsversuche protokollieren?
  log-connections: true
  # Soll Sonar neue Überprüfungsversuche während Angriffen protokollieren?
  log-during-attack: false
  # Soll Sonar jede einzelne Bewegung/Positionsänderung während der Überprüfung protokollieren?
  # Dies wird für Produktivserver nicht empfohlen, kann aber beim Auffinden von Fehlern hilfreich sein.
  debug-xyz-positions: false
  # Sollte Sonar auch Geyser (Bedrock)-Spieler überprüfen?
  # Diese Funktion ist experimentell und kann Probleme verursachen
  # Wenn dies deaktiviert ist, werden Bedrock-Spieler übersprungen
  check-geyser-players: true
  # Die Zeit, seit der der Spieler keine Pakete mehr sendet, bevor er die Verbindung trennt
  # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
  read-timeout: 8000
  # Die Zeit, seit der der Server keine Pakete mehr sendet, bevor er die Verbindung zum Spieler trennt
  # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
  write-timeout: 10000
  # Wie lange sollte ein Spieler warten, bevor er während der Überprüfung erneut verbinden kann
  # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
  rejoin-delay: 5000
  # How long should Sonar remember the amount of failed verifications for a player?
  # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
  remember-time: 120000
  # Wie lange sollte eine IP-Adresse vom Einloggen ausgeschlossen werden, wenn die Überprüfung zu oft nicht bestanden wird?
  # (Dieser Wert stellt die Zeit in Millisekunden dar: 1 Sekunde = 1000 Millisekunden)
  blacklist-time: 600000
  # Wie oft muss ein Spieler die Überprüfung nicht bestehen, um auf die Schwarze Liste gesetzt zu werden?
  # (Setzen Sie diesen Wert auf 0, um die Schwarze Liste vollständig zu deaktivieren)
  blacklist-threshold: 2
  # Liste von Protokoll-IDs, die den Server überhaupt nicht betreten dürfen
  # Die vollständige Liste aller Protokoll-IDs finden Sie hier:
  # https://wiki.vg/Protocol_version_numbers
  # Zum Beispiel hat Minecraft 1.20 die ID 763.
  blacklisted-protocols: []