#
#   /$$$$$$
#  /$$__  $$
# | $$  \__/  /$$$$$$  /$$$$$$$   /$$$$$$   /$$$$$$
# |  $$$$$$  /$$__  $$| $$__  $$ |____  $$ /$$__  $$
#  \____  $$| $$  \ $$| $$  \ $$  /$$$$$$$| $$  \__/
#  /$$  \ $$| $$  | $$| $$  | $$ /$$__  $$| $$
# |  $$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$| $$
#  \______/  \______/ |__/  |__/ \_______/|__/
#
# დახმარება გჭირდება ან კითხვა გაქვს? https://jonesdev.xyz/discord
# საწყისი კოდი: https://github.com/jonesdevelopment/sonar
# Documentation: https://docs.jonesdev.xyz/administration/configuring-sonar
# Copyright Jones Development and Sonar Contributors, licensed under GPL-3.0
#

# ზოგადი პარამეტრები Sonar-ისთვის
general:
  # შეამოწმოს თუ არა სონარმა ავტომატურად ახალი განახლებები?
  # სონარი იყენებს GitHub API_ს რომ შეამოწმოს არის თუ არა ამჟამინდელი ვერსია ყველაზე ახალი.
  check-for-updates: true
  # უნდა ჩაწეროს თუ არა Sonar-მა მოთამაშეების IP მისამართები კონსოლში?
  log-player-addresses: true
  # ერთი და იგივე IP ზე ონლაინ მოთამაშეთა მაქსიმალური რაოდენობა
  max-online-per-ip: 3

# მნიშვნელოვანი პარამეტრები თავდასხმის დაფიქსირებისთვის
# შეცვალეთ ეს მხოლოდ იმ შემთხვევაში, თუ იცით, რას აკეთებთ
attack-tracker:
  # ახალი მოთამაშეების მინიმალური რაოდენობა, რათა დაფიქსირდეს შეტევა
  min-players-for-attack: 8
  # დრო, რის შემდეგაც შეტევა დასრულებული ჩაითვლება
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  min-attack-duration: 30000
  # რამდენჯერ უნდა მოხდეს ინციდენტის დარეპორტება, რათა ჩაითვალოს ეს თავდასხმად
  # ეს რიცხვი მოქმედებს ყალბი თავდასხმის შეტყობინებების გასაფილტრად
  min-attack-threshold: 2
  # დრო, რომელიც უნდა გავიდეს ახალი შეტევის დასადგენად
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  attack-cooldown-delay: 3000

# თქვენ შეგიძლიათ დააკავშიროთ Sonar მონაცემთა ბაზას, რომ შეინახოთ ვერიფირებული მოთამაშეები თქვენი სერვერის გადატვირთვის შემდეგაც კი
# შენიშვნა: IP მისამართები ინახება უბრალო ტექსტში. თქვენ ხართ პასუხისმგებელი თქვენი მონაცემთა ბაზის უსაფრთხოებაზე!
database:
  # მონაცემთა ბაზის ტიპები, რომლებიც Sonar-ს შეუძლია გამოიყენოს უკვე შემოწმებული მოთამაშეების შესანახად
  # შესაძლო ტიპები: NONE, MYSQL, MARIADB, H2
  type: NONE
  # ფაილი სონარ_ის ფოლდერში რომელიც ინახავს H2 database_ს
  filename: verified_players
  # ჰოსტის მისამართი SQL მონაცემთა ბაზის ავთენტიფიკაციისთვის
  host: localhost
  # პორტი SQL მონაცემთა ბაზის ავთენტიფიკაციისთვის
  port: 3306
  # SQL მონაცემთა ბაზის სახელი
  name: sonar
  # მომხმარებლის სახელი SQL მონაცემთა ბაზის ავთენტიფიკაციისთვის
  username: ''
  # პაროლი SQL მონაცემთა ბაზის ავთენტიფიკაციისთვის
  password: ''
  # რამდენი დღე უნდა შეინახოს Sonar-მა შემოწმებული მოთამაშეები მონაცემთა ბაზაში?
  maximum-age: 5

# ყოველი ახალი შესვლის მოთხოვნა იქნება რიგში, რათა თავიდან აიცილოთ შემოსვლის სპამის შეტევები
# რიგი განახლდება ყოველ 1000 მილიწამში (20 ტიკი)
queue:
  # ახალი მოთამაშეების მაქსიმალური რაოდენობა, რომლებსაც შეუძლიათ შესვლა სერვერზე ყოველ 1000 მილიწამში
  max-polls: 30

# ყოველი ახალი მოთამაშე, რომელიც პირველად შემოვა, გაიგზავნება
# ლიმბო სერვერში, სადაც მოთამაშეების ვერიფიკაცია ხდება
verification:
  # როდის უნდა გადაამოწმოს Sonar-მა ახალი მოთამაშეები?
  # შესაძლო ტიპები: ALWAYS, DURING_ATTACK
  # - ALWAYS (ყოველთვის): ახალი მოთამაშეები ყოველთვის მოწმდება (რეკომენდებულია)
  # - DURING_ATTACK (შეტევის დროს): ახალი მოთამაშეები შემოწმდებიან მხოლოდ შეტევის დროს
  timing: ALWAYS
  checks:
    # ამოწმებს, მიჰყვება თუ არა მოთამაშეების ვარდნის მოძრაობა Minecraft-ის გრავიტაციის ფორმულას
    # ყველა პროგნოზირებული მოძრაობა წინასწარ არის გათვლილი შესრულების სისწრაფის შესანარჩუნებლად
    gravity:
      # უნდა შეამოწმოს თუ არა Sonar-მა მოთამაშის (ან ბოტის) გრავიტაცია? (რეკომენდებულია)
      enabled: true
      # უნდა აიძულოს თუ არა Sonar-მა მოთამაშეს შეასრულოს CAPTCHA, თუ ისინი ვერ შეასრულებენ სიმძიმის შემოწმებას?
      captcha-on-fail: false
      # ტიკების მაქსიმალური რაოდენობა რომელითაც მოთამაშე უნდა დაეცეს, რათა პლატფორმაზე დაცემა შეეძლოს. (20 ტიკი = 1 წამი)
      max-movement-ticks: 8

    # ამოწმებს, ეჯახება თუ არა მოთამაშე მათ ქვემოთ წარმოქმნილ ბლოკებს
    collision:
      # უნდა შეამოწმოს თუ არა Sonar-მა, ეტაკება თუ არა მოთამაშე ბლოკებს? (რეკომენდებულია)
      enabled: true

    # ამოწმებს, აგზავნის თუ არა კლიენტი შესაბამის პაკეტებს სატრანსპორტო საშუალებაზე დაჯდომის დროს
    vehicle:
      # უნდა შეამოწმოს თუ არა სონარმა მოთამაშე სწორად შესული თუ არა ნავში?
      enabled: true
      # კლიენტის მიერ გაგზავნილი პაკეტების მინიმალური რაოდენობა
      minimum-packets: 2

    # დააწერინეთ მოთამაშეს კოდი ჩატში, რომელიც იქნება ნაჩვენები ვირტუალურ მაპზე, რომელიც ხელში ეჭირებათ
    map-captcha:
      # როდის უნდა გააკეთებინოს Sonar-მა მოთამაშეს CAPTCHA?
      # შესაძლო ტიპები: ALWAYS, DURING_ATTACK, NEVER
      # - ALWAYS (ყოველთვის): ახალი მოთამაშეები ყოველთვის მოუწევთ CAPTCHA-ს გაკეთება.
      # - DURING_ATTACK (შეტევის დროს): ახალი მოთამაშებს მოუწევთ CAPTCHA-ს გაკეთება მხოლოდ შეტევის დროს.
      # - NEVER (არასდროს): ახალ მოთამაშეებს არასდროს მოუწევთ CAPTCHA-ს გაკეთება (Recommended).
      timing: NEVER
      # CAPTCHA-სთვის Sonar-ის მიერ გამოყენებული ფონური გამოსახულების ბილიკი
      # თუ გამოსახულება არ მოიძებნა, ფონად გამოყენებული იქნება noise ი
      # შეგიძლიათ უბრალოდ ჩაწეროთ ფაილის სახელი, თუ ის პლაგინის დირექტორიაშია
      background: ''
      # რუკის სტილი CAPTCHA (ნაგულისხმევი: 'modern').
      # ძველი დიზაინის გამოსაყენებლად დააყენეთ ეს 'legacy'.
      style: 'modern'
      # რამდენი პასუხი უნდა მოამზადოს Sonar-მა?
      # ეს ხდება ასინქრონულად (ანუ ამის გამოთვლას სერვერი არ დაელოდება) უკანა ფონზე
      precompute: 500
      # რამდენ ხანს უნდა დაელოდოს Sonar-ი, სანამ მოთამაშე ვერ გააკეთებს წარმატებულად CAPTCHA-ს?
      # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
      max-duration: 30000
      # რამდენჯერ ვერ უდნა გაიაროს CAPTCHA მოთამაშემ სანამ ვერიფიკაციას ვერ გაივლის?
      max-tries: 3
      # სიმბოლოები (ასოები და რიცხვები), რომლებიც დაშვებულია გამოჩნდეს CAPTCHA-ს პასუხში
      # არ არის რეკომენდებული რიცხვების ან ასოების დამატება, რომლებიც შეიძლება ერთმანეთს ჰგავდეს
      alphabet: 'abcdefhjkmnoprstuxyz'

    # ამოწმებს, აგზავნიან თუ არა მოთამაშეები სერვერზე რეალურ მოთამაშის მეტსახელს
    client-brand:
      # უნდა შეამოწმოს თუ არა Sonar-მა ნამდვილია თუ არა მოთამაშის სახელი? (რეკომენდებულია)
      enabled: true
      # Regex-ი მოთამაშის ბრენდების დასადასტურებლად ვერიფიკაციის დროს
      valid-regex: ^[!-~ ]+$
      # მოთამაშის კლიენტის სახელის მაქსიმალური სიგრძე ვერიფიკაციის დროს
      max-length: 64

    # Regex-ი მომხმარებლის სახელების ვერიფიკაციისთვის
    valid-name-regex: ^[a-zA-Z0-9_]+$

  # თუ ჩართულია, მოთამაშე გადავა საწყის სერვერში ვერიფიკაციის წარმატებით გავლის შემდეგ
  # ეს ფუნქცია დაემატა Mojang-ის მიერ Minecraft-ის 1.20.5 ვერსიაში
  # https://docs.jonesdev.xyz/administration/configuring-sonar/configuring-the-verification/using-1.20.5+-transfers
  transfer:
    # უნდა გადაიყვანოს თუ არა Sonar-მა მოთამაშე საწყის სერვერზე (მათი გაგდების ნაცვლად)?
    # ამისთვის, თქვენ უნდა ჩართოთ ეს ფუნქცია თქვენი სერვერის კონფიგურაციაში
    # დამატებით, შეიძლება გინდოდეთ შეამციროთ შესვლის სიხშირის ლიმიტი
    # რომელსაც ახორციელებს Velocity ან სხვა პროქსიები/პლაგინები, რადგან ეს შეიძლება ხელს უშლიდეს
    # მოთამაშის სწორად გადაყვანას
    # თუ თქვენი სერვერი საშუალებას აძლევს Bedrock მოთამაშეებს შეუერთდნენ Geyser-ის საშუალებით, დარწმუნდით, რომ დააყენეთ
    # TransferTool Geyser-ისთვის, ასე რომ Bedrock მოთამაშეები გადამისამართდებიან სწორ სერვერზე.
    # https://github.com/onebeastchris/TransferTool
    enabled: false
    # რომელ სერვერზე უნდა გადაიყვანოს Sonar-მა მოთამაშე ვერიფიკაციის გავლის შემდეგ?
    # გთხოვთ, შეიყვანოთ სერვერის IP მისამართი, რომლითაც მოთამაშეები ჩვეულებრივ უერთდებიან თქვენს სერვერს
    # მაგალითად, შეგიძლიათ ჩაწეროთ "mc.hypixel.net" ან პირდაპირი IP როგორიცაა "1.1.1.1"
    destination-host: "play.my-server.com"
    # რომელი პორტი უნდა გამოიყენოს Sonar-მა მოთამაშის საწყის სერვერზე გადაყვანისას?
    # თუ თქვენს სერვერს არ სჭირდება პორტი შესასვლელად, შეგიძლიათ დატოვოთ ეს 25565-ზე
    destination-port: 25565

  # მოთამაშის თამაშის რეჟიმი გადამოწმების დროს
  # შესაძლო ტიპები: SURVIVAL, CREATIVE, ADVENTURE
  # - SURVIVAL: ყველა UI კომპონენტი ჩანს
  # - CREATIVE: სიცოცხლის და საჭმლის მაჩვენებლები იშლება
  # - ADVENTURE: ყველა UI კომპონენტი ჩანს
  gamemode: ADVENTURE
  # დღის განათება გადამოწმების სამყაროში
  # აქ შეგიძლიათ იპოვოთ მთელი დღის დრო:
  # https://minecraft.wiki/w/Daylight_cycle
  # ეს მხოლოდ ვიზუალური პარამეტრია და არ ცვლის გადამოწმების პროცესს!
  # თუ ეს მნიშვნელობა დაყენებულია 1000-ზე, პაკეტი არ გაიგზავნება.
  time-of-day: 1000
  # Sonar ინახავს პაკეტების უმეტესობას, რომლებსაც ის უგზავნის კლიენტს, მათ შორის LoginSuccess პაკეტს.
  # რომელი მომხმარებლის სახელი უნდა გამოიყენოს Sonar-მა LoginSuccess პაკეტისთვის?
  # მომხმარებლის სახელი არ იქნება ხილული მოთამაშისთვის კლიენტის ცვლილებების გარეშე
  cached-username: "Sonar"
  # ჩაიწეროს თუ არა Sonar-მა ახალი ვერიფიკაციის მცდელობები?
  log-connections: true
  # ჩაწეროს თუ არა Sonar-მა ახალი ვერიფიკაციის მცდელობები შეტევის დროს?
  log-during-attack: false
  # ჩაიწეროს თუ არა Sonar-მა ყოველი მოძრაობა/პოზიცია ვერიფიკაციის დროს?
  # ეს არ არის რეკომენდებული აქტიურ სერვერებისთვის, მაგრამ შეიძლება გამოსადეგი იყოს ცრუ პოსიტივების გამოსასწორებლად.
  debug-xyz-positions: false
  # უნდა შეამოწმოს თუ არა Sonar-მა Geyser (Bedrock) მოთამაშეები?
  # ეს ფუნქცია ექსპერიმენტულია და შეიძლება გამოიწვიოს პრობლემები
  # თუ ეს გამორთულია, Bedrock მოთამაშეები გამოვლენილი იქნება
  check-geyser-players: false
  # დროის ოდენობა, რომელიც უნდა გავიდეს, სერვერთან კავშირის გარეშე, სანამ მოთამაშე დროებით გავარდება სერვერიდან.
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  read-timeout: 8000
  # დრო როდიდანაც სერვერმა შეწყვიტა პაკეტების გაგზავნა სანამ გააგდებს მოთამაშეს.
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  write-timeout: 10000
  # რამდენ ხანს უნდა დაელოდოს მოთამაშე ვერიფიკაციის დროს ხელახლა დაკავშირებამდე?
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  rejoin-delay: 5000
  # რამდენ ხანს უნდა ახსოვდეს Sonar-ს მოთამაშე რამდენჯერ იყო წარუმატებელი ვერიფიკაციის დროს?
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  remember-time: 120000
  # რამდენ ხნით უნდა აეკრძალოს IP მისამართს შესვლა, როდესაც ვერიფიკაციას ძალიან ხშირად ვერ აკეთებს?
  # (ეს არის ნაჩვენები მილიწამებში: 1 წამი = 1000 მილიწამი)
  blacklist-time: 600000
  # რამდენად ხშირად უნდა გაიაროს მოთამაშემ ვერიფიკაცია წარუმატებლად, რომ ის მოხვდეს შავ სიაში?
  # (დააყენეთ ეს 0 ზე, რომ მთლიანად გათიშოთ შავი სია)
  blacklist-threshold: 2
  # პროტოკოლის ID-ების სია, რომლებსაც საერთოდ არ შეუძლიათ სერვერზე შემოსვლა
  # თქვენ შეგიძლიათ იპოვოთ ყველა პროტოკოლის ID-ების სრული სია აქ:
  # https://wiki.vg/Protocol_version_numbers
  # მაგალითად, Minecraft 1.20-ს აქვს ID 763.
  blacklisted-protocols: []
