#
#   /$$$$$$
#  /$$__  $$
# | $$  \__/  /$$$$$$  /$$$$$$$   /$$$$$$   /$$$$$$
# |  $$$$$$  /$$__  $$| $$__  $$ |____  $$ /$$__  $$
#  \____  $$| $$  \ $$| $$  \ $$  /$$$$$$$| $$  \__/
#  /$$  \ $$| $$  | $$| $$  | $$ /$$__  $$| $$
# |  $$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$| $$
#  \______/  \______/ |__/  |__/ \_______/|__/
#
# Hulp nodig of vragen? https://jonesdev.xyz/discord
# Broncode: https://github.com/jonesdevelopment/sonar
# Documentatie: https://docs.jonesdev.xyz/administration/configuring-sonar
# Copyright Jones Development and Sonar Contributors, gelicentieerd onder GPL-3.0
#

# Algemene instellingen voor Sonar
general:
  # Moet Sonar automatisch controleren op nieuwe updates?
  # Sonar gebruikt de GitHub API om te controleren of de huidige versie verouderd is
  check-for-updates: true
  # Moet Sonar de IP-adressen van spelers in de console registreren?
  log-player-addresses: true
  # Maximaal aantal spelers online met hetzelfde IP-adres
  max-online-per-ip: 3

# Gevoeligheidsinstellingen voor de aanvalstracker
# Bewerk dit alleen als je weet wat je doet
attack-tracker:
  # Minimumaantal nieuwe spelers om een aanval te kunnen detecteren
  min-players-for-attack: 8
  # De hoeveelheid tijd die moet verstrijken voordat een aanval voorbij is
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  min-attack-duration: 30000
  # Aantal keren dat een incident moet worden gemeld om als aanval te worden erkend
  # Dit nummer fungeert als buffer om valse aanvalsmeldingen eruit te filteren
  min-attack-threshold: 2
  # De hoeveelheid tijd die moet verstrijken voordat een nieuwe aanval wordt gedetecteerd
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  attack-cooldown-delay: 3000

# U kunt Sonar verbinden met een database om geverifieerde spelers te behouden, zelfs nadat u uw server opnieuw hebt opgestart
# Let op: IP-adressen worden opgeslagen in platte tekst. U bent verantwoordelijk voor het veilig houden van uw database!
database:
  # Type database dat Sonar gebruikt om geverifieerde spelers op te slaan
  # Mogelijke typen: NONE, MYSQL, MARIADB, H2
  type: NONE
  # Bestand in de plugin-directory van Sonar dat wordt gebruikt voor de H2-database
  filename: verified_players
  # Adres voor authenticatie met de SQL-database
  host: localhost
  # Poort voor authenticatie met de SQL-database
  port: 3306
  # Naam van de SQL-database
  name: sonar
  # Gebruikersnaam voor authenticatie met de SQL-database
  username: ''
  # Wachtwoord voor authenticatie met de SQL-database
  password: ''
  # Hoeveel dagen moet Sonar geverifieerde spelers in de database bewaren?
  maximum-age: 5

# Elk nieuw inlogverzoek wordt in de wachtrij geplaatst om spam-join-aanvallen te voorkomen
# De wachtrij wordt elke seconde bijgewerkt (20 ticks)
queue:
  # Maximaal aantal gelijktijdige peilingen per seconde
  max-polls: 30

# Elke nieuwe speler die voor de eerste keer meedoet, wordt naar gestuurd
# een lichtgewicht limbo-server waar geavanceerde bot-controles worden uitgevoerd
verification:
  # Wanneer moet Sonar nieuwe spelers verifiëren?
  # Mogelijke typen: ALWAYS, DURING_ATTACK
  # - ALWAYS: Nieuwe spelers worden altijd gecontroleerd (Aanbevolen)
  # - DURING_ATTACK: Nieuwe spelers worden alleen gecontroleerd tijdens een aanval
  timing: ALWAYS
  checks:
    # Controleert of de valbeweging van de spelers de zwaartekrachtformule van Minecraft volgt
    # Alle voorspelde bewegingen worden vooraf berekend om prestaties te besparen
    gravity:
      # Moet Sonar controleren op geldige zwaartekracht van de cliënt? (Aanbevolen)
      enabled: true
      # Moet Sonar de speler een CAPTCHA laten oplossen als hij niet slaagt voor de zwaartekracht controle?
      captcha-on-fail: false
      # Maximaal aantal ticks dat de speler moet laten vallen om het platform te mogen raken
      max-movement-ticks: 8

    # Controleert of de speler botst met blokken die onder hem zijn gespawned
    collision:
      # Moet Sonar controleren of de speler tegen blokken botst? (Aanbevolen)
      enabled: true

    # Controleert of de klant de juiste pakketten verzendt bij het monteren van een voertuig
    vehicle:
      # Moet Sonar controleren of de speler goed in een boot stapt?
      enabled: true
      # Minimaal aantal pakketten verzonden door de cliënt
      minimum-packets: 2

    # Laat de speler een code van een virtuele kaart in de chat typen
    map-captcha:
      # Wanneer moet Sonar de speler een CAPTCHA laten oplossen?
      # Mogelijke typen: ALWAYS, DURING_ATTACK, NEVER
      # - ALWAYS: Nieuwe spelers ontvangen altijd een CAPTCHA
      # - DURING_ATTACK: Nieuwe spelers ontvangen alleen een CAPTCHA tijdens een aanval
      # - NEVER: Nieuwe spelers zullen nooit een CAPTCHA ontvangen (Aanbevolen)
      timing: NEVER
      # Pad naar de achtergrondafbeelding die Sonar gebruikt voor de CAPTCHA
      # Als de afbeelding niet wordt gevonden, wordt er een ruis gebruikt als standaardachtergrond
      # U kunt eenvoudig de naam van het bestand hier plaatsen als het bestand zich in de plugin map bevindt
      background: ''
      # Stijl van de CAPTCHA kaart (Standaard: 'modern').
      # Om het oude ontwerp te gebruiken, stel je dit in op 'legacy'.
      style: 'modern'
      # Hoeveel antwoorden moet Sonar voorbereiden?
      # Deze taak gebeurt asynchroon op de achtergrond
      precompute: 500
      # Hoe lang moet Sonar wachten totdat de speler de CAPTCHA niet haalt?
      # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
      max-duration: 30000
      # Hoe vaak moet een speler de CAPTCHA niet halen voordat de verificatie mislukt?
      max-tries: 3
      # Tekens (letters en cijfers) die mogen voorkomen in het antwoord op de CAPTCHA
      # Het wordt niet aanbevolen om cijfers of letters toe te voegen die op elkaar lijken
      alphabet: 'abcdefhjkmnoprstuxyz'

    # Controleert of de speler een geldig Minecraft-klantmerk naar de server verzendt
    client-brand:
      # Moet Sonar controleren op geldige Minecraft-klantmerk? (Aanbevolen)
      enabled: true
      # Regex voor het valideren van Minecraft-klantmerken tijdens verificatie
      valid-regex: ^[!-~ ]+$
      # Maximale lengte van het Minecraft-klantmerk tijdens verificatie
      max-length: 64

    # Regex voor het valideren van gebruikersnamen tijdens verificatie
    valid-name-regex: ^[a-zA-Z0-9_]+$

  # Indien ingeschakeld, wordt de speler teruggestuurd naar de oorspronkelijke server
  # nadat u de bot-verificatie met succes heeft doorstaan.
  # Deze functie is geïntroduceerd door Mojang in Minecraft versie 1.20.5
  # https://docs.jonesdev.xyz/administration/configuring-sonar/configuring-the-verification/using-1.20.5+-transfers
  transfer:
    # Moet Sonar de speler overbrengen naar de oorspronkelijke server (in plaats van hem te schoppen)?
    # Om dit te laten werken, moet u de functie inschakelen in de configuratie van uw server
    # Bovendien wilt u mogelijk de beperking van de inlegsnelheid verminderen
    # uitgevoerd door Velocity van andere proxy's/plugins, omdat dit de
    # speler wordt niet correct weergegeven.
    # Als je server toestaat dat Bedrock spelers meedoen via Geyser, zorg er dan voor dat je
    # TransferTool voor Geyser, zodat Bedrock spelers worden doorgestuurd naar de juiste server.
    # https://github.com/onebeastchris/TransferTool
    enabled: false
    # Naar welke server moet Sonar de speler overbrengen wanneer de verificatie is geslaagd?
    # Voer het server-IP in dat door spelers wordt gebruikt om normaal verbinding te maken met uw server.
    # U kunt bijvoorbeeld "mc.hypixel.net" of een direct IP-adres zoals "1.1.1.1" invoeren
    destination-host: "play.my-server.com"
    # Welke poort moet Sonar gebruiken bij het overbrengen van de speler naar de oorspronkelijke server?
    # Als uw server geen poort nodig heeft om verbinding mee te maken, kunt u dit op 25565 laten staan.
    destination-port: 25565

  # De spelmodus van de speler tijdens verificatie
  # Mogelijke typen: SURVIVAL, CREATIVE, ADVENTURE
  # - SURVIVAL: alle UI-componenten zijn zichtbaar
  # - CREATIVE: gezondheid en honger zijn verborgen
  # - ADVENTURE: alle UI-componenten zijn zichtbaar
  gamemode: ADVENTURE
  # Zomertijd in de verificatiewereld
  # Je kunt alle zomertijd hier vinden:
  # https://minecraft.wiki/w/Daylight_cycle
  # Dit is alleen een visuele instelling en verandert niets aan het verificatieproces!
  # Als deze waarde is ingesteld op 1000, wordt het pakket niet verzonden.
  time-of-day: 1000
  # Sonar cached de meeste pakketten die het naar de client stuurt, inclusief het LoginSuccess pakket.
  # Welke gebruikersnaam moet Sonar gebruiken voor het LoginSucces pakket?
  # De gebruikersnaam zal niet zichtbaar zijn voor de speler zonder client aanpassingen
  cached-username: "Sonar"
  # Moet Sonar nieuwe verificatiepogingen registreren?
  log-connections: true
  # Moet Sonar nieuwe verificatiepogingen registreren tijdens aanvallen?
  log-during-attack: false
  # Moet Sonar elke beweging/positieverandering tijdens de verificatie registreren?
  # Dit wordt niet aanbevolen voor productieservers, maar kan nuttig zijn bij het opsporen van fouten.
  debug-xyz-positions: false
  # Moet Sonar ook Geyser (Bedrock) spelers controleren?
  # Deze functie is experimenteel en kan problemen veroorzaken
  # Als dit is uitgeschakeld, worden Bedrock-spelers overgeslagen
  check-geyser-players: false
  # De hoeveelheid tijd die moet verstrijken voordat een speler een time-out krijgt
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  read-timeout: 8000
  # De tijd sinds de speler stopte met het verzenden van pakketten voordat de verbinding werd verbroken
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  rejoin-delay: 5000
  # De tijd sinds de server stopte met het versturen van pakketten voordat de verbinding met de speler werd verbroken
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  write-timeout: 10000
  # Hoe lang moet Sonar het aantal mislukte verificaties voor een speler onthouden?
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  remember-time: 120000
  # Hoe lang moet een IP-adres worden ontzegd om in te loggen als de verificatie te vaak mislukt?
  # (Deze waarde vertegenwoordigt de tijd in milliseconden: 1 seconde = 1000 milliseconden)
  blacklist-time: 600000
  # Hoe vaak moet een speler de verificatie niet doorstaan om op de zwarte lijst te worden geplaatst?
  # (Stel deze waarde in op 0 om de zwarte lijst volledig uit te schakelen)
  blacklist-threshold: 2
  # Lijst met protocol-ID's die helemaal geen verbinding kunnen maken met de server
  # De volledige lijst met alle protocol-ID's vindt u hier:
  # https://wiki.vg/Protocol_version_numbers
  # Minecraft 1.20 heeft bijvoorbeeld de ID 763.
  blacklisted-protocols: []
